#!/bin/sh
case $1 in
        server)
        if [ "$2"x = ""x ]; then
            ssserver -c /etc/shadowsocks/server.js
        else
            ssserver -c $2
        fi
        ;;
        client)
        if [ "$2"x = ""x ]; then
            sslocal -c /etc/shadowsocks/007.js
        else
            sslocal -c $2
        fi
        ;;
esac